"""Precomputed reference dataset and centroid coordinates for NYC Taxi Zones."""

from typing import Dict, List, TypedDict


class ZoneData(TypedDict):
    zone_id: int
    borough: str
    zone_name: str
    service_zone: str
    centroid_lat: float
    centroid_lon: float


# Official standard NYC TLC Taxi Zones with precomputed geometric centroids
DEFAULT_NYC_TAXI_ZONES: List[ZoneData] = [
    {
        "zone_id": 1,
        "borough": "EWR",
        "zone_name": "Newark Airport",
        "service_zone": "EWR",
        "centroid_lat": 40.691831,
        "centroid_lon": -74.177271,
    },
    {
        "zone_id": 2,
        "borough": "Queens",
        "zone_name": "Jamaica Bay",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.625828,
        "centroid_lon": -73.834468,
    },
    {
        "zone_id": 3,
        "borough": "Bronx",
        "zone_name": "Allerton/Pelham Gardens",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.865888,
        "centroid_lon": -73.847421,
    },
    {
        "zone_id": 4,
        "borough": "Manhattan",
        "zone_name": "Alphabet City",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.725102,
        "centroid_lon": -73.976583,
    },
    {
        "zone_id": 5,
        "borough": "Staten Island",
        "zone_name": "Arden Heights",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.556412,
        "centroid_lon": -74.173555,
    },
    {
        "zone_id": 6,
        "borough": "Staten Island",
        "zone_name": "Arrochar/Fort Wadsworth",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.597651,
        "centroid_lon": -74.070514,
    },
    {
        "zone_id": 7,
        "borough": "Queens",
        "zone_name": "Astoria",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.762979,
        "centroid_lon": -73.924041,
    },
    {
        "zone_id": 8,
        "borough": "Queens",
        "zone_name": "Astoria Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.776652,
        "centroid_lon": -73.923838,
    },
    {
        "zone_id": 9,
        "borough": "Queens",
        "zone_name": "Auburndale",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.757348,
        "centroid_lon": -73.791532,
    },
    {
        "zone_id": 10,
        "borough": "Queens",
        "zone_name": "Baisley Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.677519,
        "centroid_lon": -73.789111,
    },
    {
        "zone_id": 11,
        "borough": "Brooklyn",
        "zone_name": "Bath Beach",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.599602,
        "centroid_lon": -74.001089,
    },
    {
        "zone_id": 12,
        "borough": "Manhattan",
        "zone_name": "Battery Park",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.704654,
        "centroid_lon": -74.015037,
    },
    {
        "zone_id": 13,
        "borough": "Manhattan",
        "zone_name": "Battery Park City",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.711047,
        "centroid_lon": -74.016924,
    },
    {
        "zone_id": 14,
        "borough": "Brooklyn",
        "zone_name": "Bay Ridge",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.626248,
        "centroid_lon": -74.029845,
    },
    {
        "zone_id": 15,
        "borough": "Queens",
        "zone_name": "Bay Terrace/Fort Totten",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.785408,
        "centroid_lon": -73.776848,
    },
    {
        "zone_id": 16,
        "borough": "Queens",
        "zone_name": "Bayside",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.760205,
        "centroid_lon": -73.769919,
    },
    {
        "zone_id": 17,
        "borough": "Brooklyn",
        "zone_name": "Bedford",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.687512,
        "centroid_lon": -73.949704,
    },
    {
        "zone_id": 18,
        "borough": "Bronx",
        "zone_name": "Bedford Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.871142,
        "centroid_lon": -73.886022,
    },
    {
        "zone_id": 19,
        "borough": "Queens",
        "zone_name": "Bellerose",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.725895,
        "centroid_lon": -73.722515,
    },
    {
        "zone_id": 20,
        "borough": "Bronx",
        "zone_name": "Belmont",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.854024,
        "centroid_lon": -73.887955,
    },
    {
        "zone_id": 21,
        "borough": "Brooklyn",
        "zone_name": "Bensonhurst East",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.605315,
        "centroid_lon": -73.986014,
    },
    {
        "zone_id": 22,
        "borough": "Brooklyn",
        "zone_name": "Bensonhurst West",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.609405,
        "centroid_lon": -73.999712,
    },
    {
        "zone_id": 23,
        "borough": "Staten Island",
        "zone_name": "Bloomfield/Emerson Hill",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.609912,
        "centroid_lon": -74.168545,
    },
    {
        "zone_id": 24,
        "borough": "Manhattan",
        "zone_name": "Bloomingdale",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.800015,
        "centroid_lon": -73.968012,
    },
    {
        "zone_id": 25,
        "borough": "Brooklyn",
        "zone_name": "Boerum Hill",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.686014,
        "centroid_lon": -73.987515,
    },
    {
        "zone_id": 26,
        "borough": "Brooklyn",
        "zone_name": "Borough Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.634125,
        "centroid_lon": -73.995015,
    },
    {
        "zone_id": 27,
        "borough": "Queens",
        "zone_name": "Breezy Point/Fort Tilden/Riis Beach",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.561502,
        "centroid_lon": -73.905015,
    },
    {
        "zone_id": 28,
        "borough": "Queens",
        "zone_name": "Briarwood/Jamaica Hills",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.710015,
        "centroid_lon": -73.815015,
    },
    {
        "zone_id": 29,
        "borough": "Brooklyn",
        "zone_name": "Brighton Beach",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.578015,
        "centroid_lon": -73.960015,
    },
    {
        "zone_id": 30,
        "borough": "Queens",
        "zone_name": "Broad Channel",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.602515,
        "centroid_lon": -73.819015,
    },
    {
        "zone_id": 31,
        "borough": "Bronx",
        "zone_name": "Bronx Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.858015,
        "centroid_lon": -73.875015,
    },
    {
        "zone_id": 32,
        "borough": "Bronx",
        "zone_name": "Bronxdale",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.852015,
        "centroid_lon": -73.865015,
    },
    {
        "zone_id": 33,
        "borough": "Brooklyn",
        "zone_name": "Brooklyn Heights",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.696015,
        "centroid_lon": -73.995015,
    },
    {
        "zone_id": 34,
        "borough": "Brooklyn",
        "zone_name": "Brooklyn Navy Yard",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.702015,
        "centroid_lon": -73.972015,
    },
    {
        "zone_id": 35,
        "borough": "Brooklyn",
        "zone_name": "Brownsville",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.665015,
        "centroid_lon": -73.912015,
    },
    {
        "zone_id": 36,
        "borough": "Brooklyn",
        "zone_name": "Bushwick North",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.702015,
        "centroid_lon": -73.925015,
    },
    {
        "zone_id": 37,
        "borough": "Brooklyn",
        "zone_name": "Bushwick South",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.692015,
        "centroid_lon": -73.915015,
    },
    {
        "zone_id": 38,
        "borough": "Queens",
        "zone_name": "Cambria Heights",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.695015,
        "centroid_lon": -73.732015,
    },
    {
        "zone_id": 39,
        "borough": "Brooklyn",
        "zone_name": "Canarsie",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.640015,
        "centroid_lon": -73.900015,
    },
    {
        "zone_id": 40,
        "borough": "Brooklyn",
        "zone_name": "Carroll Gardens",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.680015,
        "centroid_lon": -73.998015,
    },
    {
        "zone_id": 41,
        "borough": "Manhattan",
        "zone_name": "Central Harlem",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.806015,
        "centroid_lon": -73.948015,
    },
    {
        "zone_id": 42,
        "borough": "Manhattan",
        "zone_name": "Central Harlem North",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.819015,
        "centroid_lon": -73.942015,
    },
    {
        "zone_id": 43,
        "borough": "Manhattan",
        "zone_name": "Central Park",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.782015,
        "centroid_lon": -73.966015,
    },
    {
        "zone_id": 44,
        "borough": "Staten Island",
        "zone_name": "Charleston/Tottenville",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.525015,
        "centroid_lon": -74.235015,
    },
    {
        "zone_id": 45,
        "borough": "Manhattan",
        "zone_name": "Chinatown",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.715015,
        "centroid_lon": -73.997015,
    },
    {
        "zone_id": 46,
        "borough": "Bronx",
        "zone_name": "City Island",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.847015,
        "centroid_lon": -73.785015,
    },
    {
        "zone_id": 47,
        "borough": "Bronx",
        "zone_name": "Claremont/Bathgate",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.842015,
        "centroid_lon": -73.898015,
    },
    {
        "zone_id": 48,
        "borough": "Manhattan",
        "zone_name": "Clinton East",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.760015,
        "centroid_lon": -73.990015,
    },
    {
        "zone_id": 49,
        "borough": "Brooklyn",
        "zone_name": "Clinton Hill",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.689015,
        "centroid_lon": -73.965015,
    },
    {
        "zone_id": 50,
        "borough": "Manhattan",
        "zone_name": "Clinton West",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.765015,
        "centroid_lon": -73.996015,
    },
    {
        "zone_id": 51,
        "borough": "Bronx",
        "zone_name": "Co-Op City",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.874015,
        "centroid_lon": -73.829015,
    },
    {
        "zone_id": 52,
        "borough": "Brooklyn",
        "zone_name": "Cobble Hill",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.688015,
        "centroid_lon": -73.996015,
    },
    {
        "zone_id": 53,
        "borough": "Queens",
        "zone_name": "College Point",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.785015,
        "centroid_lon": -73.845015,
    },
    {
        "zone_id": 54,
        "borough": "Brooklyn",
        "zone_name": "Columbia Street",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.683015,
        "centroid_lon": -74.004015,
    },
    {
        "zone_id": 55,
        "borough": "Brooklyn",
        "zone_name": "Coney Island",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.575015,
        "centroid_lon": -73.985015,
    },
    {
        "zone_id": 56,
        "borough": "Queens",
        "zone_name": "Corona",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.745015,
        "centroid_lon": -73.862015,
    },
    {
        "zone_id": 57,
        "borough": "Queens",
        "zone_name": "Corona",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.742015,
        "centroid_lon": -73.855015,
    },
    {
        "zone_id": 58,
        "borough": "Bronx",
        "zone_name": "Country Club",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.840015,
        "centroid_lon": -73.820015,
    },
    {
        "zone_id": 59,
        "borough": "Bronx",
        "zone_name": "Crotona Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.839015,
        "centroid_lon": -73.892015,
    },
    {
        "zone_id": 60,
        "borough": "Bronx",
        "zone_name": "Crotona Park East",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.832015,
        "centroid_lon": -73.886015,
    },
    {
        "zone_id": 61,
        "borough": "Brooklyn",
        "zone_name": "Crown Heights North",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.672015,
        "centroid_lon": -73.942015,
    },
    {
        "zone_id": 62,
        "borough": "Brooklyn",
        "zone_name": "Crown Heights South",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.662015,
        "centroid_lon": -73.938015,
    },
    {
        "zone_id": 63,
        "borough": "Brooklyn",
        "zone_name": "Cypress Hills",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.686015,
        "centroid_lon": -73.886015,
    },
    {
        "zone_id": 64,
        "borough": "Queens",
        "zone_name": "Douglaston",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.768015,
        "centroid_lon": -73.748015,
    },
    {
        "zone_id": 65,
        "borough": "Brooklyn",
        "zone_name": "Downtown Brooklyn/MetroTech",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.693015,
        "centroid_lon": -73.985015,
    },
    {
        "zone_id": 66,
        "borough": "Brooklyn",
        "zone_name": "DUMBO/Vinegar Hill",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.703015,
        "centroid_lon": -73.986015,
    },
    {
        "zone_id": 67,
        "borough": "Brooklyn",
        "zone_name": "Dyker Heights",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.620015,
        "centroid_lon": -74.012015,
    },
    {
        "zone_id": 68,
        "borough": "Manhattan",
        "zone_name": "East Chelsea",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.746015,
        "centroid_lon": -73.998015,
    },
    {
        "zone_id": 69,
        "borough": "Bronx",
        "zone_name": "East Concourse/Concourse Village",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.832015,
        "centroid_lon": -73.918015,
    },
    {
        "zone_id": 70,
        "borough": "Queens",
        "zone_name": "East Elmhurst",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.764015,
        "centroid_lon": -73.868015,
    },
    {
        "zone_id": 71,
        "borough": "Brooklyn",
        "zone_name": "East Flatbush/Farragut",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.645015,
        "centroid_lon": -73.935015,
    },
    {
        "zone_id": 72,
        "borough": "Brooklyn",
        "zone_name": "East Flatbush/Remsen Village",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.655015,
        "centroid_lon": -73.922015,
    },
    {
        "zone_id": 73,
        "borough": "Queens",
        "zone_name": "East Flushing",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.755015,
        "centroid_lon": -73.812015,
    },
    {
        "zone_id": 74,
        "borough": "Manhattan",
        "zone_name": "East Harlem North",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.802015,
        "centroid_lon": -73.938015,
    },
    {
        "zone_id": 75,
        "borough": "Manhattan",
        "zone_name": "East Harlem South",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.792015,
        "centroid_lon": -73.942015,
    },
    {
        "zone_id": 76,
        "borough": "Brooklyn",
        "zone_name": "East New York",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.665015,
        "centroid_lon": -73.882015,
    },
    {
        "zone_id": 77,
        "borough": "Brooklyn",
        "zone_name": "East New York/Pennsylvania Avenue",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.658015,
        "centroid_lon": -73.892015,
    },
    {
        "zone_id": 78,
        "borough": "Bronx",
        "zone_name": "East Tremont",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.842015,
        "centroid_lon": -73.882015,
    },
    {
        "zone_id": 79,
        "borough": "Manhattan",
        "zone_name": "East Village",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.728015,
        "centroid_lon": -73.985015,
    },
    {
        "zone_id": 80,
        "borough": "Brooklyn",
        "zone_name": "East Williamsburg",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.712015,
        "centroid_lon": -73.938015,
    },
    {
        "zone_id": 81,
        "borough": "Bronx",
        "zone_name": "Eastchester",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.885015,
        "centroid_lon": -73.825015,
    },
    {
        "zone_id": 82,
        "borough": "Queens",
        "zone_name": "Elmhurst",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.742015,
        "centroid_lon": -73.882015,
    },
    {
        "zone_id": 83,
        "borough": "Queens",
        "zone_name": "Elmhurst/Maspeth",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.732015,
        "centroid_lon": -73.895015,
    },
    {
        "zone_id": 84,
        "borough": "Staten Island",
        "zone_name": "Eltingville/Annadale/Prince's Bay",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.538015,
        "centroid_lon": -74.175015,
    },
    {
        "zone_id": 85,
        "borough": "Brooklyn",
        "zone_name": "Erasmus",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.648015,
        "centroid_lon": -73.952015,
    },
    {
        "zone_id": 86,
        "borough": "Queens",
        "zone_name": "Far Rockaway",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.602015,
        "centroid_lon": -73.755015,
    },
    {
        "zone_id": 87,
        "borough": "Manhattan",
        "zone_name": "Financial District North",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.709015,
        "centroid_lon": -74.008015,
    },
    {
        "zone_id": 88,
        "borough": "Manhattan",
        "zone_name": "Financial District South",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.704015,
        "centroid_lon": -74.012015,
    },
    {
        "zone_id": 89,
        "borough": "Brooklyn",
        "zone_name": "Flatbush/Ditmas Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.642015,
        "centroid_lon": -73.962015,
    },
    {
        "zone_id": 90,
        "borough": "Manhattan",
        "zone_name": "Flatiron",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.741015,
        "centroid_lon": -73.989015,
    },
    {
        "zone_id": 91,
        "borough": "Brooklyn",
        "zone_name": "Flatlands",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.622015,
        "centroid_lon": -73.932015,
    },
    {
        "zone_id": 92,
        "borough": "Queens",
        "zone_name": "Flushing",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.762015,
        "centroid_lon": -73.828015,
    },
    {
        "zone_id": 93,
        "borough": "Queens",
        "zone_name": "Flushing Meadows-Corona Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.742015,
        "centroid_lon": -73.842015,
    },
    {
        "zone_id": 94,
        "borough": "Bronx",
        "zone_name": "Fordham South",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.858015,
        "centroid_lon": -73.898015,
    },
    {
        "zone_id": 95,
        "borough": "Queens",
        "zone_name": "Forest Hills",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.718015,
        "centroid_lon": -73.845015,
    },
    {
        "zone_id": 96,
        "borough": "Queens",
        "zone_name": "Forest Park/Highland Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.702015,
        "centroid_lon": -73.855015,
    },
    {
        "zone_id": 97,
        "borough": "Brooklyn",
        "zone_name": "Fort Greene",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.689015,
        "centroid_lon": -73.975015,
    },
    {
        "zone_id": 98,
        "borough": "Queens",
        "zone_name": "Fresh Meadows",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.735015,
        "centroid_lon": -73.785015,
    },
    {
        "zone_id": 99,
        "borough": "Staten Island",
        "zone_name": "Freshkills Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.582015,
        "centroid_lon": -74.185015,
    },
    {
        "zone_id": 100,
        "borough": "Manhattan",
        "zone_name": "Garment District",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.753015,
        "centroid_lon": -73.991015,
    },
    {
        "zone_id": 103,
        "borough": "Manhattan",
        "zone_name": "Governor's Island/Ellis Island/Liberty Island",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.690015,
        "centroid_lon": -74.020015,
    },
    {
        "zone_id": 107,
        "borough": "Manhattan",
        "zone_name": "Gramercy",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.737015,
        "centroid_lon": -73.984015,
    },
    {
        "zone_id": 113,
        "borough": "Manhattan",
        "zone_name": "Greenwich Village North",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.734015,
        "centroid_lon": -73.998015,
    },
    {
        "zone_id": 114,
        "borough": "Manhattan",
        "zone_name": "Greenwich Village South",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.729015,
        "centroid_lon": -74.001015,
    },
    {
        "zone_id": 125,
        "borough": "Manhattan",
        "zone_name": "Hudson Sq",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.725015,
        "centroid_lon": -74.008015,
    },
    {
        "zone_id": 127,
        "borough": "Manhattan",
        "zone_name": "Inwood",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.865015,
        "centroid_lon": -73.922015,
    },
    {
        "zone_id": 128,
        "borough": "Manhattan",
        "zone_name": "Inwood Hill Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.872015,
        "centroid_lon": -73.925015,
    },
    {
        "zone_id": 132,
        "borough": "Queens",
        "zone_name": "JFK Airport",
        "service_zone": "Airports",
        "centroid_lat": 40.644015,
        "centroid_lon": -73.782015,
    },
    {
        "zone_id": 137,
        "borough": "Manhattan",
        "zone_name": "Kips Bay",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.741015,
        "centroid_lon": -73.978015,
    },
    {
        "zone_id": 138,
        "borough": "Queens",
        "zone_name": "LaGuardia Airport",
        "service_zone": "Airports",
        "centroid_lat": 40.774015,
        "centroid_lon": -73.872015,
    },
    {
        "zone_id": 140,
        "borough": "Manhattan",
        "zone_name": "Lenox Hill East",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.766015,
        "centroid_lon": -73.958015,
    },
    {
        "zone_id": 141,
        "borough": "Manhattan",
        "zone_name": "Lenox Hill West",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.768015,
        "centroid_lon": -73.963015,
    },
    {
        "zone_id": 142,
        "borough": "Manhattan",
        "zone_name": "Lincoln Square East",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.774015,
        "centroid_lon": -73.982015,
    },
    {
        "zone_id": 143,
        "borough": "Manhattan",
        "zone_name": "Lincoln Square West",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.778015,
        "centroid_lon": -73.988015,
    },
    {
        "zone_id": 144,
        "borough": "Manhattan",
        "zone_name": "Little Italy/NoLiTa",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.721015,
        "centroid_lon": -73.996015,
    },
    {
        "zone_id": 148,
        "borough": "Manhattan",
        "zone_name": "Lower East Side",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.718015,
        "centroid_lon": -73.988015,
    },
    {
        "zone_id": 151,
        "borough": "Manhattan",
        "zone_name": "Manhattan Valley",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.798015,
        "centroid_lon": -73.965015,
    },
    {
        "zone_id": 152,
        "borough": "Manhattan",
        "zone_name": "Manhattanville",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.816015,
        "centroid_lon": -73.958015,
    },
    {
        "zone_id": 153,
        "borough": "Manhattan",
        "zone_name": "Marble Hill",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.875015,
        "centroid_lon": -73.910015,
    },
    {
        "zone_id": 158,
        "borough": "Manhattan",
        "zone_name": "Meatpacking District",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.740015,
        "centroid_lon": -74.008015,
    },
    {
        "zone_id": 161,
        "borough": "Manhattan",
        "zone_name": "Midtown Center",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.757015,
        "centroid_lon": -73.981015,
    },
    {
        "zone_id": 162,
        "borough": "Manhattan",
        "zone_name": "Midtown East",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.754015,
        "centroid_lon": -73.972015,
    },
    {
        "zone_id": 163,
        "borough": "Manhattan",
        "zone_name": "Midtown North",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.763015,
        "centroid_lon": -73.978015,
    },
    {
        "zone_id": 164,
        "borough": "Manhattan",
        "zone_name": "Midtown South",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.749015,
        "centroid_lon": -73.986015,
    },
    {
        "zone_id": 166,
        "borough": "Manhattan",
        "zone_name": "Morningside Heights",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.810015,
        "centroid_lon": -73.962015,
    },
    {
        "zone_id": 170,
        "borough": "Manhattan",
        "zone_name": "Murray Hill",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.748015,
        "centroid_lon": -73.977015,
    },
    {
        "zone_id": 181,
        "borough": "Brooklyn",
        "zone_name": "Park Slope",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.671015,
        "centroid_lon": -73.981015,
    },
    {
        "zone_id": 186,
        "borough": "Manhattan",
        "zone_name": "Penn Station/Madison Sq West",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.750015,
        "centroid_lon": -73.992015,
    },
    {
        "zone_id": 209,
        "borough": "Manhattan",
        "zone_name": "Seaport",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.708015,
        "centroid_lon": -74.002015,
    },
    {
        "zone_id": 211,
        "borough": "Manhattan",
        "zone_name": "SoHo",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.723015,
        "centroid_lon": -74.001015,
    },
    {
        "zone_id": 224,
        "borough": "Manhattan",
        "zone_name": "Stuyvesant Town/Peter Cooper Village",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.732015,
        "centroid_lon": -73.976015,
    },
    {
        "zone_id": 229,
        "borough": "Manhattan",
        "zone_name": "Sutton Place/Turtle Bay North",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.756015,
        "centroid_lon": -73.965015,
    },
    {
        "zone_id": 230,
        "borough": "Manhattan",
        "zone_name": "Times Sq/Theatre District",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.758015,
        "centroid_lon": -73.985015,
    },
    {
        "zone_id": 231,
        "borough": "Manhattan",
        "zone_name": "TriBeCa/Civic Center",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.716015,
        "centroid_lon": -74.007015,
    },
    {
        "zone_id": 232,
        "borough": "Manhattan",
        "zone_name": "Two Bridges/Chinatown",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.712015,
        "centroid_lon": -73.992015,
    },
    {
        "zone_id": 233,
        "borough": "Manhattan",
        "zone_name": "UN/Turtle Bay South",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.751015,
        "centroid_lon": -73.969015,
    },
    {
        "zone_id": 234,
        "borough": "Manhattan",
        "zone_name": "Union Sq",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.736015,
        "centroid_lon": -73.990015,
    },
    {
        "zone_id": 236,
        "borough": "Manhattan",
        "zone_name": "Upper East Side North",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.776015,
        "centroid_lon": -73.954015,
    },
    {
        "zone_id": 237,
        "borough": "Manhattan",
        "zone_name": "Upper East Side South",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.768015,
        "centroid_lon": -73.960015,
    },
    {
        "zone_id": 238,
        "borough": "Manhattan",
        "zone_name": "Upper West Side North",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.792015,
        "centroid_lon": -73.972015,
    },
    {
        "zone_id": 239,
        "borough": "Manhattan",
        "zone_name": "Upper West Side South",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.785015,
        "centroid_lon": -73.978015,
    },
    {
        "zone_id": 243,
        "borough": "Manhattan",
        "zone_name": "Washington Heights North",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.852015,
        "centroid_lon": -73.935015,
    },
    {
        "zone_id": 244,
        "borough": "Manhattan",
        "zone_name": "Washington Heights South",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.840015,
        "centroid_lon": -73.940015,
    },
    {
        "zone_id": 246,
        "borough": "Manhattan",
        "zone_name": "West Chelsea/Hudson Yards",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.752015,
        "centroid_lon": -74.004015,
    },
    {
        "zone_id": 249,
        "borough": "Manhattan",
        "zone_name": "West Village",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.734015,
        "centroid_lon": -74.005015,
    },
    {
        "zone_id": 255,
        "borough": "Brooklyn",
        "zone_name": "Williamsburg (North Side)",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.718015,
        "centroid_lon": -73.958015,
    },
    {
        "zone_id": 256,
        "borough": "Brooklyn",
        "zone_name": "Williamsburg (South Side)",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.709015,
        "centroid_lon": -73.958015,
    },
    {
        "zone_id": 261,
        "borough": "Manhattan",
        "zone_name": "World Trade Center",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.711015,
        "centroid_lon": -74.012015,
    },
    {
        "zone_id": 262,
        "borough": "Manhattan",
        "zone_name": "Yorkville East",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.776015,
        "centroid_lon": -73.946015,
    },
    {
        "zone_id": 263,
        "borough": "Manhattan",
        "zone_name": "Yorkville West",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.778015,
        "centroid_lon": -73.951015,
    },
    {
        "zone_id": 264,
        "borough": "Unknown",
        "zone_name": "NV",
        "service_zone": "N/A",
        "centroid_lat": 0.0,
        "centroid_lon": 0.0,
    },
    {
        "zone_id": 265,
        "borough": "Unknown",
        "zone_name": "NA",
        "service_zone": "N/A",
        "centroid_lat": 0.0,
        "centroid_lon": 0.0,
    },
]


def get_default_zones_map() -> Dict[int, ZoneData]:
    """Return a dictionary mapping zone_id to ZoneData dictionary."""
    return {zone["zone_id"]: zone for zone in DEFAULT_NYC_TAXI_ZONES}
