"""NYC TLC Taxi Zones reference dataset with representative centroid coordinates.

Data Notes:
- Zone metadata (LocationID, Borough, Zone Name, Service Zone) corresponds to the
  official NYC TLC Taxi Zone Lookup table (https://d37ci6vzurychx.cloudfront.net/misc/taxi+_zone_lookup.csv).
- Numeric centroid coordinates (centroid_lat, centroid_lon) are representative coordinates
  for each NYC taxi zone and airport footprint, used explicitly for UI map plotting only
  pending calculation from the official TLC shapefile (see ADR-011).
"""

from typing import Dict, List, TypedDict


class ZoneData(TypedDict):
    zone_id: int
    borough: str
    zone_name: str
    service_zone: str
    centroid_lat: float
    centroid_lon: float


# Official standard NYC TLC Taxi Zones (IDs 1 through 265)
DEFAULT_NYC_TAXI_ZONES: List[ZoneData] = [
    {
        "zone_id": 1,
        "borough": "EWR",
        "zone_name": "Newark Airport",
        "service_zone": "EWR",
        "centroid_lat": 40.691831,
        "centroid_lon": -74.177271,
    },
    {
        "zone_id": 2,
        "borough": "Queens",
        "zone_name": "Jamaica Bay",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.625828,
        "centroid_lon": -73.834468,
    },
    {
        "zone_id": 3,
        "borough": "Bronx",
        "zone_name": "Allerton/Pelham Gardens",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.865888,
        "centroid_lon": -73.847421,
    },
    {
        "zone_id": 4,
        "borough": "Manhattan",
        "zone_name": "Alphabet City",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.725102,
        "centroid_lon": -73.976583,
    },
    {
        "zone_id": 5,
        "borough": "Staten Island",
        "zone_name": "Arden Heights",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.556412,
        "centroid_lon": -74.173555,
    },
    {
        "zone_id": 6,
        "borough": "Staten Island",
        "zone_name": "Arrochar/Fort Wadsworth",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.597651,
        "centroid_lon": -74.070514,
    },
    {
        "zone_id": 7,
        "borough": "Queens",
        "zone_name": "Astoria",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.762979,
        "centroid_lon": -73.924041,
    },
    {
        "zone_id": 8,
        "borough": "Queens",
        "zone_name": "Astoria Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.776652,
        "centroid_lon": -73.923838,
    },
    {
        "zone_id": 9,
        "borough": "Queens",
        "zone_name": "Auburndale",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.757348,
        "centroid_lon": -73.791532,
    },
    {
        "zone_id": 10,
        "borough": "Queens",
        "zone_name": "Baisley Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.677519,
        "centroid_lon": -73.789111,
    },
    {
        "zone_id": 11,
        "borough": "Brooklyn",
        "zone_name": "Bath Beach",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.599602,
        "centroid_lon": -74.001089,
    },
    {
        "zone_id": 12,
        "borough": "Manhattan",
        "zone_name": "Battery Park",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.704654,
        "centroid_lon": -74.015037,
    },
    {
        "zone_id": 13,
        "borough": "Manhattan",
        "zone_name": "Battery Park City",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.711047,
        "centroid_lon": -74.016924,
    },
    {
        "zone_id": 14,
        "borough": "Brooklyn",
        "zone_name": "Bay Ridge",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.626248,
        "centroid_lon": -74.029845,
    },
    {
        "zone_id": 15,
        "borough": "Queens",
        "zone_name": "Bay Terrace/Fort Totten",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.785408,
        "centroid_lon": -73.776848,
    },
    {
        "zone_id": 16,
        "borough": "Queens",
        "zone_name": "Bayside",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.760205,
        "centroid_lon": -73.769919,
    },
    {
        "zone_id": 17,
        "borough": "Brooklyn",
        "zone_name": "Bedford",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.687512,
        "centroid_lon": -73.949704,
    },
    {
        "zone_id": 18,
        "borough": "Bronx",
        "zone_name": "Bedford Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.871142,
        "centroid_lon": -73.886022,
    },
    {
        "zone_id": 19,
        "borough": "Queens",
        "zone_name": "Bellerose",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.725895,
        "centroid_lon": -73.722515,
    },
    {
        "zone_id": 20,
        "borough": "Bronx",
        "zone_name": "Belmont",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.854024,
        "centroid_lon": -73.887955,
    },
    {
        "zone_id": 21,
        "borough": "Brooklyn",
        "zone_name": "Bensonhurst East",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.605315,
        "centroid_lon": -73.986014,
    },
    {
        "zone_id": 22,
        "borough": "Brooklyn",
        "zone_name": "Bensonhurst West",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.609405,
        "centroid_lon": -73.999712,
    },
    {
        "zone_id": 23,
        "borough": "Staten Island",
        "zone_name": "Bloomfield/Emerson Hill",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.609912,
        "centroid_lon": -74.168545,
    },
    {
        "zone_id": 24,
        "borough": "Manhattan",
        "zone_name": "Bloomingdale",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.800015,
        "centroid_lon": -73.968012,
    },
    {
        "zone_id": 25,
        "borough": "Brooklyn",
        "zone_name": "Boerum Hill",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.686014,
        "centroid_lon": -73.987515,
    },
    {
        "zone_id": 26,
        "borough": "Brooklyn",
        "zone_name": "Borough Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.634125,
        "centroid_lon": -73.995015,
    },
    {
        "zone_id": 27,
        "borough": "Queens",
        "zone_name": "Breezy Point/Fort Tilden/Riis Beach",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.561502,
        "centroid_lon": -73.905015,
    },
    {
        "zone_id": 28,
        "borough": "Queens",
        "zone_name": "Briarwood/Jamaica Hills",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.710015,
        "centroid_lon": -73.815015,
    },
    {
        "zone_id": 29,
        "borough": "Brooklyn",
        "zone_name": "Brighton Beach",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.578015,
        "centroid_lon": -73.960015,
    },
    {
        "zone_id": 30,
        "borough": "Queens",
        "zone_name": "Broad Channel",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.602515,
        "centroid_lon": -73.819015,
    },
    {
        "zone_id": 31,
        "borough": "Bronx",
        "zone_name": "Bronx Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.858015,
        "centroid_lon": -73.875015,
    },
    {
        "zone_id": 32,
        "borough": "Bronx",
        "zone_name": "Bronxdale",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.852015,
        "centroid_lon": -73.865015,
    },
    {
        "zone_id": 33,
        "borough": "Brooklyn",
        "zone_name": "Brooklyn Heights",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.696015,
        "centroid_lon": -73.995015,
    },
    {
        "zone_id": 34,
        "borough": "Brooklyn",
        "zone_name": "Brooklyn Navy Yard",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.702015,
        "centroid_lon": -73.972015,
    },
    {
        "zone_id": 35,
        "borough": "Brooklyn",
        "zone_name": "Brownsville",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.665015,
        "centroid_lon": -73.912015,
    },
    {
        "zone_id": 36,
        "borough": "Brooklyn",
        "zone_name": "Bushwick North",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.702015,
        "centroid_lon": -73.925015,
    },
    {
        "zone_id": 37,
        "borough": "Brooklyn",
        "zone_name": "Bushwick South",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.692015,
        "centroid_lon": -73.915015,
    },
    {
        "zone_id": 38,
        "borough": "Queens",
        "zone_name": "Cambria Heights",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.695015,
        "centroid_lon": -73.732015,
    },
    {
        "zone_id": 39,
        "borough": "Brooklyn",
        "zone_name": "Canarsie",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.640015,
        "centroid_lon": -73.900015,
    },
    {
        "zone_id": 40,
        "borough": "Brooklyn",
        "zone_name": "Carroll Gardens",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.680015,
        "centroid_lon": -73.998015,
    },
    {
        "zone_id": 41,
        "borough": "Manhattan",
        "zone_name": "Central Harlem",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.806015,
        "centroid_lon": -73.948015,
    },
    {
        "zone_id": 42,
        "borough": "Manhattan",
        "zone_name": "Central Harlem North",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.819015,
        "centroid_lon": -73.942015,
    },
    {
        "zone_id": 43,
        "borough": "Manhattan",
        "zone_name": "Central Park",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.782015,
        "centroid_lon": -73.966015,
    },
    {
        "zone_id": 44,
        "borough": "Staten Island",
        "zone_name": "Charleston/Tottenville",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.525015,
        "centroid_lon": -74.235015,
    },
    {
        "zone_id": 45,
        "borough": "Manhattan",
        "zone_name": "Chinatown",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.715015,
        "centroid_lon": -73.997015,
    },
    {
        "zone_id": 46,
        "borough": "Bronx",
        "zone_name": "City Island",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.847015,
        "centroid_lon": -73.785015,
    },
    {
        "zone_id": 47,
        "borough": "Bronx",
        "zone_name": "Claremont/Bathgate",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.842015,
        "centroid_lon": -73.898015,
    },
    {
        "zone_id": 48,
        "borough": "Manhattan",
        "zone_name": "Clinton East",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.760015,
        "centroid_lon": -73.990015,
    },
    {
        "zone_id": 49,
        "borough": "Brooklyn",
        "zone_name": "Clinton Hill",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.689015,
        "centroid_lon": -73.965015,
    },
    {
        "zone_id": 50,
        "borough": "Manhattan",
        "zone_name": "Clinton West",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.765015,
        "centroid_lon": -73.996015,
    },
    {
        "zone_id": 51,
        "borough": "Bronx",
        "zone_name": "Co-Op City",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.874015,
        "centroid_lon": -73.829015,
    },
    {
        "zone_id": 52,
        "borough": "Brooklyn",
        "zone_name": "Cobble Hill",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.688015,
        "centroid_lon": -73.996015,
    },
    {
        "zone_id": 53,
        "borough": "Queens",
        "zone_name": "College Point",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.785015,
        "centroid_lon": -73.845015,
    },
    {
        "zone_id": 54,
        "borough": "Brooklyn",
        "zone_name": "Columbia Street",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.683015,
        "centroid_lon": -74.004015,
    },
    {
        "zone_id": 55,
        "borough": "Brooklyn",
        "zone_name": "Coney Island",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.575015,
        "centroid_lon": -73.985015,
    },
    {
        "zone_id": 56,
        "borough": "Queens",
        "zone_name": "Corona",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.745015,
        "centroid_lon": -73.862015,
    },
    {
        "zone_id": 57,
        "borough": "Queens",
        "zone_name": "Corona",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.742015,
        "centroid_lon": -73.855015,
    },
    {
        "zone_id": 58,
        "borough": "Bronx",
        "zone_name": "Country Club",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.840015,
        "centroid_lon": -73.820015,
    },
    {
        "zone_id": 59,
        "borough": "Bronx",
        "zone_name": "Crotona Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.839015,
        "centroid_lon": -73.892015,
    },
    {
        "zone_id": 60,
        "borough": "Bronx",
        "zone_name": "Crotona Park East",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.832015,
        "centroid_lon": -73.886015,
    },
    {
        "zone_id": 61,
        "borough": "Brooklyn",
        "zone_name": "Crown Heights North",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.672015,
        "centroid_lon": -73.942015,
    },
    {
        "zone_id": 62,
        "borough": "Brooklyn",
        "zone_name": "Crown Heights South",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.662015,
        "centroid_lon": -73.938015,
    },
    {
        "zone_id": 63,
        "borough": "Brooklyn",
        "zone_name": "Cypress Hills",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.686015,
        "centroid_lon": -73.886015,
    },
    {
        "zone_id": 64,
        "borough": "Queens",
        "zone_name": "Douglaston",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.768015,
        "centroid_lon": -73.748015,
    },
    {
        "zone_id": 65,
        "borough": "Brooklyn",
        "zone_name": "Downtown Brooklyn/MetroTech",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.693015,
        "centroid_lon": -73.985015,
    },
    {
        "zone_id": 66,
        "borough": "Brooklyn",
        "zone_name": "DUMBO/Vinegar Hill",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.703015,
        "centroid_lon": -73.986015,
    },
    {
        "zone_id": 67,
        "borough": "Brooklyn",
        "zone_name": "Dyker Heights",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.620015,
        "centroid_lon": -74.012015,
    },
    {
        "zone_id": 68,
        "borough": "Manhattan",
        "zone_name": "East Chelsea",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.746015,
        "centroid_lon": -73.998015,
    },
    {
        "zone_id": 69,
        "borough": "Bronx",
        "zone_name": "East Concourse/Concourse Village",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.832015,
        "centroid_lon": -73.918015,
    },
    {
        "zone_id": 70,
        "borough": "Queens",
        "zone_name": "East Elmhurst",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.764015,
        "centroid_lon": -73.868015,
    },
    {
        "zone_id": 71,
        "borough": "Brooklyn",
        "zone_name": "East Flatbush/Farragut",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.645015,
        "centroid_lon": -73.935015,
    },
    {
        "zone_id": 72,
        "borough": "Brooklyn",
        "zone_name": "East Flatbush/Remsen Village",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.655015,
        "centroid_lon": -73.922015,
    },
    {
        "zone_id": 73,
        "borough": "Queens",
        "zone_name": "East Flushing",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.755015,
        "centroid_lon": -73.812015,
    },
    {
        "zone_id": 74,
        "borough": "Manhattan",
        "zone_name": "East Harlem North",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.802015,
        "centroid_lon": -73.938015,
    },
    {
        "zone_id": 75,
        "borough": "Manhattan",
        "zone_name": "East Harlem South",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.792015,
        "centroid_lon": -73.942015,
    },
    {
        "zone_id": 76,
        "borough": "Brooklyn",
        "zone_name": "East New York",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.665015,
        "centroid_lon": -73.882015,
    },
    {
        "zone_id": 77,
        "borough": "Brooklyn",
        "zone_name": "East New York/Pennsylvania Avenue",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.658015,
        "centroid_lon": -73.892015,
    },
    {
        "zone_id": 78,
        "borough": "Bronx",
        "zone_name": "East Tremont",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.842015,
        "centroid_lon": -73.882015,
    },
    {
        "zone_id": 79,
        "borough": "Manhattan",
        "zone_name": "East Village",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.728015,
        "centroid_lon": -73.985015,
    },
    {
        "zone_id": 80,
        "borough": "Brooklyn",
        "zone_name": "East Williamsburg",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.712015,
        "centroid_lon": -73.938015,
    },
    {
        "zone_id": 81,
        "borough": "Bronx",
        "zone_name": "Eastchester",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.885015,
        "centroid_lon": -73.825015,
    },
    {
        "zone_id": 82,
        "borough": "Queens",
        "zone_name": "Elmhurst",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.742015,
        "centroid_lon": -73.882015,
    },
    {
        "zone_id": 83,
        "borough": "Queens",
        "zone_name": "Elmhurst/Maspeth",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.732015,
        "centroid_lon": -73.895015,
    },
    {
        "zone_id": 84,
        "borough": "Staten Island",
        "zone_name": "Eltingville/Annadale/Prince's Bay",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.538015,
        "centroid_lon": -74.175015,
    },
    {
        "zone_id": 85,
        "borough": "Brooklyn",
        "zone_name": "Erasmus",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.648015,
        "centroid_lon": -73.952015,
    },
    {
        "zone_id": 86,
        "borough": "Queens",
        "zone_name": "Far Rockaway",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.602015,
        "centroid_lon": -73.755015,
    },
    {
        "zone_id": 87,
        "borough": "Manhattan",
        "zone_name": "Financial District North",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.709015,
        "centroid_lon": -74.008015,
    },
    {
        "zone_id": 88,
        "borough": "Manhattan",
        "zone_name": "Financial District South",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.704015,
        "centroid_lon": -74.012015,
    },
    {
        "zone_id": 89,
        "borough": "Brooklyn",
        "zone_name": "Flatbush/Ditmas Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.642015,
        "centroid_lon": -73.962015,
    },
    {
        "zone_id": 90,
        "borough": "Manhattan",
        "zone_name": "Flatiron",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.741015,
        "centroid_lon": -73.989015,
    },
    {
        "zone_id": 91,
        "borough": "Brooklyn",
        "zone_name": "Flatlands",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.622015,
        "centroid_lon": -73.932015,
    },
    {
        "zone_id": 92,
        "borough": "Queens",
        "zone_name": "Flushing",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.762015,
        "centroid_lon": -73.828015,
    },
    {
        "zone_id": 93,
        "borough": "Queens",
        "zone_name": "Flushing Meadows-Corona Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.742015,
        "centroid_lon": -73.842015,
    },
    {
        "zone_id": 94,
        "borough": "Bronx",
        "zone_name": "Fordham South",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.858015,
        "centroid_lon": -73.898015,
    },
    {
        "zone_id": 95,
        "borough": "Queens",
        "zone_name": "Forest Hills",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.718015,
        "centroid_lon": -73.845015,
    },
    {
        "zone_id": 96,
        "borough": "Queens",
        "zone_name": "Forest Park/Highland Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.702015,
        "centroid_lon": -73.855015,
    },
    {
        "zone_id": 97,
        "borough": "Brooklyn",
        "zone_name": "Fort Greene",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.689015,
        "centroid_lon": -73.975015,
    },
    {
        "zone_id": 98,
        "borough": "Queens",
        "zone_name": "Fresh Meadows",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.735015,
        "centroid_lon": -73.785015,
    },
    {
        "zone_id": 99,
        "borough": "Staten Island",
        "zone_name": "Freshkills Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.582015,
        "centroid_lon": -74.185015,
    },
    {
        "zone_id": 100,
        "borough": "Manhattan",
        "zone_name": "Garment District",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.753015,
        "centroid_lon": -73.991015,
    },
    {
        "zone_id": 101,
        "borough": "Queens",
        "zone_name": "Glen Oaks",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.748015,
        "centroid_lon": -73.712015,
    },
    {
        "zone_id": 102,
        "borough": "Queens",
        "zone_name": "Glendale",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.700015,
        "centroid_lon": -73.882015,
    },
    {
        "zone_id": 103,
        "borough": "Manhattan",
        "zone_name": "Governor's Island/Ellis Island/Liberty Island",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.690015,
        "centroid_lon": -74.020015,
    },
    {
        "zone_id": 104,
        "borough": "Brooklyn",
        "zone_name": "Governors Island/Ellis Island/Liberty Island",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.690015,
        "centroid_lon": -74.020015,
    },
    {
        "zone_id": 105,
        "borough": "Manhattan",
        "zone_name": "Governor's Island/Ellis Island/Liberty Island",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.690015,
        "centroid_lon": -74.020015,
    },
    {
        "zone_id": 106,
        "borough": "Brooklyn",
        "zone_name": "Gowanus",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.675015,
        "centroid_lon": -73.995015,
    },
    {
        "zone_id": 107,
        "borough": "Manhattan",
        "zone_name": "Gramercy",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.737015,
        "centroid_lon": -73.984015,
    },
    {
        "zone_id": 108,
        "borough": "Brooklyn",
        "zone_name": "Gravesend",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.595015,
        "centroid_lon": -73.975015,
    },
    {
        "zone_id": 109,
        "borough": "Staten Island",
        "zone_name": "Great Kills",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.552015,
        "centroid_lon": -74.152015,
    },
    {
        "zone_id": 110,
        "borough": "Staten Island",
        "zone_name": "Great Kills Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.542015,
        "centroid_lon": -74.135015,
    },
    {
        "zone_id": 111,
        "borough": "Brooklyn",
        "zone_name": "Green-Wood Cemetery",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.655015,
        "centroid_lon": -73.995015,
    },
    {
        "zone_id": 112,
        "borough": "Brooklyn",
        "zone_name": "Greenpoint",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.728015,
        "centroid_lon": -73.948015,
    },
    {
        "zone_id": 113,
        "borough": "Manhattan",
        "zone_name": "Greenwich Village North",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.734015,
        "centroid_lon": -73.998015,
    },
    {
        "zone_id": 114,
        "borough": "Manhattan",
        "zone_name": "Greenwich Village South",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.729015,
        "centroid_lon": -74.001015,
    },
    {
        "zone_id": 115,
        "borough": "Staten Island",
        "zone_name": "Grymes Hill/Clifton",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.618015,
        "centroid_lon": -74.085015,
    },
    {
        "zone_id": 116,
        "borough": "Manhattan",
        "zone_name": "Hamilton Heights",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.825015,
        "centroid_lon": -73.950015,
    },
    {
        "zone_id": 117,
        "borough": "Queens",
        "zone_name": "Hammels/Arverne",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.588015,
        "centroid_lon": -73.798015,
    },
    {
        "zone_id": 118,
        "borough": "Staten Island",
        "zone_name": "Heartland Village/Todt Hill",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.598015,
        "centroid_lon": -74.135015,
    },
    {
        "zone_id": 119,
        "borough": "Bronx",
        "zone_name": "Highbridge",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.838015,
        "centroid_lon": -73.928015,
    },
    {
        "zone_id": 120,
        "borough": "Manhattan",
        "zone_name": "Highbridge Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.845015,
        "centroid_lon": -73.930015,
    },
    {
        "zone_id": 121,
        "borough": "Queens",
        "zone_name": "Hillcrest/Pomonok",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.728015,
        "centroid_lon": -73.805015,
    },
    {
        "zone_id": 122,
        "borough": "Queens",
        "zone_name": "Hollis",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.710015,
        "centroid_lon": -73.768015,
    },
    {
        "zone_id": 123,
        "borough": "Brooklyn",
        "zone_name": "Homecrest",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.598015,
        "centroid_lon": -73.958015,
    },
    {
        "zone_id": 124,
        "borough": "Queens",
        "zone_name": "Howard Beach",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.655015,
        "centroid_lon": -73.842015,
    },
    {
        "zone_id": 125,
        "borough": "Manhattan",
        "zone_name": "Hudson Sq",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.725015,
        "centroid_lon": -74.008015,
    },
    {
        "zone_id": 126,
        "borough": "Bronx",
        "zone_name": "Hunts Point",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.812015,
        "centroid_lon": -73.882015,
    },
    {
        "zone_id": 127,
        "borough": "Manhattan",
        "zone_name": "Inwood",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.865015,
        "centroid_lon": -73.922015,
    },
    {
        "zone_id": 128,
        "borough": "Manhattan",
        "zone_name": "Inwood Hill Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.872015,
        "centroid_lon": -73.925015,
    },
    {
        "zone_id": 129,
        "borough": "Queens",
        "zone_name": "Jackson Heights",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.752015,
        "centroid_lon": -73.885015,
    },
    {
        "zone_id": 130,
        "borough": "Queens",
        "zone_name": "Jamaica",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.702015,
        "centroid_lon": -73.798015,
    },
    {
        "zone_id": 131,
        "borough": "Queens",
        "zone_name": "Jamaica Estates",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.720015,
        "centroid_lon": -73.785015,
    },
    {
        "zone_id": 132,
        "borough": "Queens",
        "zone_name": "JFK Airport",
        "service_zone": "Airports",
        "centroid_lat": 40.644015,
        "centroid_lon": -73.782015,
    },
    {
        "zone_id": 133,
        "borough": "Brooklyn",
        "zone_name": "Kensington",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.638015,
        "centroid_lon": -73.978015,
    },
    {
        "zone_id": 134,
        "borough": "Queens",
        "zone_name": "Kew Gardens",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.710015,
        "centroid_lon": -73.830015,
    },
    {
        "zone_id": 135,
        "borough": "Queens",
        "zone_name": "Kew Gardens Hills",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.725015,
        "centroid_lon": -73.822015,
    },
    {
        "zone_id": 136,
        "borough": "Bronx",
        "zone_name": "Kingsbridge Heights",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.875015,
        "centroid_lon": -73.898015,
    },
    {
        "zone_id": 137,
        "borough": "Manhattan",
        "zone_name": "Kips Bay",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.741015,
        "centroid_lon": -73.978015,
    },
    {
        "zone_id": 138,
        "borough": "Queens",
        "zone_name": "LaGuardia Airport",
        "service_zone": "Airports",
        "centroid_lat": 40.774015,
        "centroid_lon": -73.872015,
    },
    {
        "zone_id": 139,
        "borough": "Queens",
        "zone_name": "Laurelton",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.672015,
        "centroid_lon": -73.748015,
    },
    {
        "zone_id": 140,
        "borough": "Manhattan",
        "zone_name": "Lenox Hill East",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.766015,
        "centroid_lon": -73.958015,
    },
    {
        "zone_id": 141,
        "borough": "Manhattan",
        "zone_name": "Lenox Hill West",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.768015,
        "centroid_lon": -73.963015,
    },
    {
        "zone_id": 142,
        "borough": "Manhattan",
        "zone_name": "Lincoln Square East",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.774015,
        "centroid_lon": -73.982015,
    },
    {
        "zone_id": 143,
        "borough": "Manhattan",
        "zone_name": "Lincoln Square West",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.778015,
        "centroid_lon": -73.988015,
    },
    {
        "zone_id": 144,
        "borough": "Manhattan",
        "zone_name": "Little Italy/NoLiTa",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.721015,
        "centroid_lon": -73.996015,
    },
    {
        "zone_id": 145,
        "borough": "Queens",
        "zone_name": "Long Island City/Hunters Point",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.742015,
        "centroid_lon": -73.955015,
    },
    {
        "zone_id": 146,
        "borough": "Queens",
        "zone_name": "Long Island City/Queens Plaza",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.750015,
        "centroid_lon": -73.938015,
    },
    {
        "zone_id": 147,
        "borough": "Bronx",
        "zone_name": "Longwood",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.822015,
        "centroid_lon": -73.895015,
    },
    {
        "zone_id": 148,
        "borough": "Manhattan",
        "zone_name": "Lower East Side",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.718015,
        "centroid_lon": -73.988015,
    },
    {
        "zone_id": 149,
        "borough": "Brooklyn",
        "zone_name": "Madison",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.608015,
        "centroid_lon": -73.948015,
    },
    {
        "zone_id": 150,
        "borough": "Brooklyn",
        "zone_name": "Manhattan Beach",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.580015,
        "centroid_lon": -73.942015,
    },
    {
        "zone_id": 151,
        "borough": "Manhattan",
        "zone_name": "Manhattan Valley",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.798015,
        "centroid_lon": -73.965015,
    },
    {
        "zone_id": 152,
        "borough": "Manhattan",
        "zone_name": "Manhattanville",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.816015,
        "centroid_lon": -73.958015,
    },
    {
        "zone_id": 153,
        "borough": "Manhattan",
        "zone_name": "Marble Hill",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.875015,
        "centroid_lon": -73.910015,
    },
    {
        "zone_id": 154,
        "borough": "Brooklyn",
        "zone_name": "Marine Park/Floyd Bennett Field",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.605015,
        "centroid_lon": -73.905015,
    },
    {
        "zone_id": 155,
        "borough": "Brooklyn",
        "zone_name": "Marine Park/Mill Basin",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.612015,
        "centroid_lon": -73.918015,
    },
    {
        "zone_id": 156,
        "borough": "Staten Island",
        "zone_name": "Mariners Harbor",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.635015,
        "centroid_lon": -74.155015,
    },
    {
        "zone_id": 157,
        "borough": "Queens",
        "zone_name": "Maspeth",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.722015,
        "centroid_lon": -73.908015,
    },
    {
        "zone_id": 158,
        "borough": "Manhattan",
        "zone_name": "Meatpacking District",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.740015,
        "centroid_lon": -74.008015,
    },
    {
        "zone_id": 159,
        "borough": "Bronx",
        "zone_name": "Melrose South",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.820015,
        "centroid_lon": -73.915015,
    },
    {
        "zone_id": 160,
        "borough": "Queens",
        "zone_name": "Middle Village",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.715015,
        "centroid_lon": -73.882015,
    },
    {
        "zone_id": 161,
        "borough": "Manhattan",
        "zone_name": "Midtown Center",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.757015,
        "centroid_lon": -73.981015,
    },
    {
        "zone_id": 162,
        "borough": "Manhattan",
        "zone_name": "Midtown East",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.754015,
        "centroid_lon": -73.972015,
    },
    {
        "zone_id": 163,
        "borough": "Manhattan",
        "zone_name": "Midtown North",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.763015,
        "centroid_lon": -73.978015,
    },
    {
        "zone_id": 164,
        "borough": "Manhattan",
        "zone_name": "Midtown South",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.749015,
        "centroid_lon": -73.986015,
    },
    {
        "zone_id": 165,
        "borough": "Brooklyn",
        "zone_name": "Midwood",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.622015,
        "centroid_lon": -73.962015,
    },
    {
        "zone_id": 166,
        "borough": "Manhattan",
        "zone_name": "Morningside Heights",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.810015,
        "centroid_lon": -73.962015,
    },
    {
        "zone_id": 167,
        "borough": "Bronx",
        "zone_name": "Morrisania/Melrose",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.830015,
        "centroid_lon": -73.908015,
    },
    {
        "zone_id": 168,
        "borough": "Bronx",
        "zone_name": "Mott Haven/Port Morris",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.808015,
        "centroid_lon": -73.918015,
    },
    {
        "zone_id": 169,
        "borough": "Bronx",
        "zone_name": "Mount Hope",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.848015,
        "centroid_lon": -73.905015,
    },
    {
        "zone_id": 170,
        "borough": "Manhattan",
        "zone_name": "Murray Hill",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.748015,
        "centroid_lon": -73.977015,
    },
    {
        "zone_id": 171,
        "borough": "Queens",
        "zone_name": "Murray Hill-Queens",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.765015,
        "centroid_lon": -73.805015,
    },
    {
        "zone_id": 172,
        "borough": "Staten Island",
        "zone_name": "New Dorp/Beacon Hill",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.575015,
        "centroid_lon": -74.115015,
    },
    {
        "zone_id": 173,
        "borough": "Queens",
        "zone_name": "North Corona",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.755015,
        "centroid_lon": -73.865015,
    },
    {
        "zone_id": 174,
        "borough": "Bronx",
        "zone_name": "Norwood",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.878015,
        "centroid_lon": -73.878015,
    },
    {
        "zone_id": 175,
        "borough": "Queens",
        "zone_name": "Oakland Gardens",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.745015,
        "centroid_lon": -73.755015,
    },
    {
        "zone_id": 176,
        "borough": "Staten Island",
        "zone_name": "Oakwood",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.560015,
        "centroid_lon": -74.125015,
    },
    {
        "zone_id": 177,
        "borough": "Brooklyn",
        "zone_name": "Ocean Hill",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.678015,
        "centroid_lon": -73.912015,
    },
    {
        "zone_id": 178,
        "borough": "Brooklyn",
        "zone_name": "Ocean Parkway South",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.608015,
        "centroid_lon": -73.968015,
    },
    {
        "zone_id": 179,
        "borough": "Queens",
        "zone_name": "Old Astoria",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.772015,
        "centroid_lon": -73.935015,
    },
    {
        "zone_id": 180,
        "borough": "Queens",
        "zone_name": "Ozone Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.680015,
        "centroid_lon": -73.845015,
    },
    {
        "zone_id": 181,
        "borough": "Brooklyn",
        "zone_name": "Park Slope",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.671015,
        "centroid_lon": -73.981015,
    },
    {
        "zone_id": 182,
        "borough": "Bronx",
        "zone_name": "Parkchester",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.835015,
        "centroid_lon": -73.860015,
    },
    {
        "zone_id": 183,
        "borough": "Bronx",
        "zone_name": "Pelham Bay",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.850015,
        "centroid_lon": -73.832015,
    },
    {
        "zone_id": 184,
        "borough": "Bronx",
        "zone_name": "Pelham Bay Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.870015,
        "centroid_lon": -73.805015,
    },
    {
        "zone_id": 185,
        "borough": "Bronx",
        "zone_name": "Pelham Parkway",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.855015,
        "centroid_lon": -73.858015,
    },
    {
        "zone_id": 186,
        "borough": "Manhattan",
        "zone_name": "Penn Station/Madison Sq West",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.750015,
        "centroid_lon": -73.992015,
    },
    {
        "zone_id": 187,
        "borough": "Staten Island",
        "zone_name": "Port Richmond",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.635015,
        "centroid_lon": -74.135015,
    },
    {
        "zone_id": 188,
        "borough": "Brooklyn",
        "zone_name": "Prospect-Lefferts Gardens",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.658015,
        "centroid_lon": -73.952015,
    },
    {
        "zone_id": 189,
        "borough": "Brooklyn",
        "zone_name": "Prospect Heights",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.678015,
        "centroid_lon": -73.968015,
    },
    {
        "zone_id": 190,
        "borough": "Brooklyn",
        "zone_name": "Prospect Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.660015,
        "centroid_lon": -73.970015,
    },
    {
        "zone_id": 191,
        "borough": "Queens",
        "zone_name": "Queens Village",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.718015,
        "centroid_lon": -73.738015,
    },
    {
        "zone_id": 192,
        "borough": "Queens",
        "zone_name": "Queensboro Hill",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.742015,
        "centroid_lon": -73.822015,
    },
    {
        "zone_id": 193,
        "borough": "Queens",
        "zone_name": "Queensbridge/Ravenswood",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.755015,
        "centroid_lon": -73.945015,
    },
    {
        "zone_id": 194,
        "borough": "Manhattan",
        "zone_name": "Randalls Island",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.792015,
        "centroid_lon": -73.922015,
    },
    {
        "zone_id": 195,
        "borough": "Brooklyn",
        "zone_name": "Red Hook",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.675015,
        "centroid_lon": -74.010015,
    },
    {
        "zone_id": 196,
        "borough": "Queens",
        "zone_name": "Rego Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.725015,
        "centroid_lon": -73.858015,
    },
    {
        "zone_id": 197,
        "borough": "Queens",
        "zone_name": "Richmond Hill",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.698015,
        "centroid_lon": -73.828015,
    },
    {
        "zone_id": 198,
        "borough": "Queens",
        "zone_name": "Ridgewood",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.705015,
        "centroid_lon": -73.900015,
    },
    {
        "zone_id": 199,
        "borough": "Bronx",
        "zone_name": "Rikers Island",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.792015,
        "centroid_lon": -73.888015,
    },
    {
        "zone_id": 200,
        "borough": "Bronx",
        "zone_name": "Riverdale/North Riverdale/Fieldston",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.898015,
        "centroid_lon": -73.905015,
    },
    {
        "zone_id": 201,
        "borough": "Queens",
        "zone_name": "Rockaway Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.578015,
        "centroid_lon": -73.835015,
    },
    {
        "zone_id": 202,
        "borough": "Manhattan",
        "zone_name": "Roosevelt Island",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.760015,
        "centroid_lon": -73.950015,
    },
    {
        "zone_id": 203,
        "borough": "Queens",
        "zone_name": "Rosedale",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.658015,
        "centroid_lon": -73.725015,
    },
    {
        "zone_id": 204,
        "borough": "Staten Island",
        "zone_name": "Rossville/Woodrow",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.545015,
        "centroid_lon": -74.205015,
    },
    {
        "zone_id": 205,
        "borough": "Queens",
        "zone_name": "Saint Albans",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.692015,
        "centroid_lon": -73.762015,
    },
    {
        "zone_id": 206,
        "borough": "Staten Island",
        "zone_name": "Saint George/New Brighton",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.642015,
        "centroid_lon": -74.085015,
    },
    {
        "zone_id": 207,
        "borough": "Queens",
        "zone_name": "Saint Michaels Cemetery/Woodside",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.762015,
        "centroid_lon": -73.902015,
    },
    {
        "zone_id": 208,
        "borough": "Bronx",
        "zone_name": "Schuylerville/Edgewater Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.825015,
        "centroid_lon": -73.820015,
    },
    {
        "zone_id": 209,
        "borough": "Manhattan",
        "zone_name": "Seaport",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.708015,
        "centroid_lon": -74.002015,
    },
    {
        "zone_id": 210,
        "borough": "Brooklyn",
        "zone_name": "Sheepshead Bay",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.592015,
        "centroid_lon": -73.948015,
    },
    {
        "zone_id": 211,
        "borough": "Manhattan",
        "zone_name": "SoHo",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.723015,
        "centroid_lon": -74.001015,
    },
    {
        "zone_id": 212,
        "borough": "Bronx",
        "zone_name": "Soundview/Bruckner",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.822015,
        "centroid_lon": -73.868015,
    },
    {
        "zone_id": 213,
        "borough": "Bronx",
        "zone_name": "Soundview/Castle Hill",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.818015,
        "centroid_lon": -73.850015,
    },
    {
        "zone_id": 214,
        "borough": "Staten Island",
        "zone_name": "South Beach/Dongan Hills",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.585015,
        "centroid_lon": -74.085015,
    },
    {
        "zone_id": 215,
        "borough": "Queens",
        "zone_name": "South Jamaica",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.682015,
        "centroid_lon": -73.792015,
    },
    {
        "zone_id": 216,
        "borough": "Queens",
        "zone_name": "South Ozone Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.672015,
        "centroid_lon": -73.818015,
    },
    {
        "zone_id": 217,
        "borough": "Brooklyn",
        "zone_name": "South Williamsburg",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.705015,
        "centroid_lon": -73.958015,
    },
    {
        "zone_id": 218,
        "borough": "Queens",
        "zone_name": "Springfield Gardens North",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.680015,
        "centroid_lon": -73.760015,
    },
    {
        "zone_id": 219,
        "borough": "Queens",
        "zone_name": "Springfield Gardens South",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.660015,
        "centroid_lon": -73.762015,
    },
    {
        "zone_id": 220,
        "borough": "Bronx",
        "zone_name": "Spuyten Duyvil/Kingsbridge",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.885015,
        "centroid_lon": -73.912015,
    },
    {
        "zone_id": 221,
        "borough": "Staten Island",
        "zone_name": "Stapleton",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.628015,
        "centroid_lon": -74.078015,
    },
    {
        "zone_id": 222,
        "borough": "Brooklyn",
        "zone_name": "Starrett City",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.650015,
        "centroid_lon": -73.885015,
    },
    {
        "zone_id": 223,
        "borough": "Queens",
        "zone_name": "Steinway",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.772015,
        "centroid_lon": -73.905015,
    },
    {
        "zone_id": 224,
        "borough": "Manhattan",
        "zone_name": "Stuyvesant Town/Peter Cooper Village",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.732015,
        "centroid_lon": -73.976015,
    },
    {
        "zone_id": 225,
        "borough": "Brooklyn",
        "zone_name": "Stuyvesant Heights",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.682015,
        "centroid_lon": -73.935015,
    },
    {
        "zone_id": 226,
        "borough": "Queens",
        "zone_name": "Sunnyside",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.745015,
        "centroid_lon": -73.922015,
    },
    {
        "zone_id": 227,
        "borough": "Brooklyn",
        "zone_name": "Sunset Park East",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.645015,
        "centroid_lon": -74.000015,
    },
    {
        "zone_id": 228,
        "borough": "Brooklyn",
        "zone_name": "Sunset Park West",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.650015,
        "centroid_lon": -74.015015,
    },
    {
        "zone_id": 229,
        "borough": "Manhattan",
        "zone_name": "Sutton Place/Turtle Bay North",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.756015,
        "centroid_lon": -73.965015,
    },
    {
        "zone_id": 230,
        "borough": "Manhattan",
        "zone_name": "Times Sq/Theatre District",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.758015,
        "centroid_lon": -73.985015,
    },
    {
        "zone_id": 231,
        "borough": "Manhattan",
        "zone_name": "TriBeCa/Civic Center",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.716015,
        "centroid_lon": -74.007015,
    },
    {
        "zone_id": 232,
        "borough": "Manhattan",
        "zone_name": "Two Bridges/Chinatown",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.712015,
        "centroid_lon": -73.992015,
    },
    {
        "zone_id": 233,
        "borough": "Manhattan",
        "zone_name": "UN/Turtle Bay South",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.751015,
        "centroid_lon": -73.969015,
    },
    {
        "zone_id": 234,
        "borough": "Manhattan",
        "zone_name": "Union Sq",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.736015,
        "centroid_lon": -73.990015,
    },
    {
        "zone_id": 235,
        "borough": "Bronx",
        "zone_name": "University Heights/Morris Heights",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.852015,
        "centroid_lon": -73.915015,
    },
    {
        "zone_id": 236,
        "borough": "Manhattan",
        "zone_name": "Upper East Side North",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.776015,
        "centroid_lon": -73.954015,
    },
    {
        "zone_id": 237,
        "borough": "Manhattan",
        "zone_name": "Upper East Side South",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.768015,
        "centroid_lon": -73.960015,
    },
    {
        "zone_id": 238,
        "borough": "Manhattan",
        "zone_name": "Upper West Side North",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.792015,
        "centroid_lon": -73.972015,
    },
    {
        "zone_id": 239,
        "borough": "Manhattan",
        "zone_name": "Upper West Side South",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.785015,
        "centroid_lon": -73.978015,
    },
    {
        "zone_id": 240,
        "borough": "Bronx",
        "zone_name": "Van Cortlandt Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.898015,
        "centroid_lon": -73.885015,
    },
    {
        "zone_id": 241,
        "borough": "Bronx",
        "zone_name": "Van Cortlandt Village",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.882015,
        "centroid_lon": -73.895015,
    },
    {
        "zone_id": 242,
        "borough": "Bronx",
        "zone_name": "Van Nest/Morris Park",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.850015,
        "centroid_lon": -73.860015,
    },
    {
        "zone_id": 243,
        "borough": "Manhattan",
        "zone_name": "Washington Heights North",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.852015,
        "centroid_lon": -73.935015,
    },
    {
        "zone_id": 244,
        "borough": "Manhattan",
        "zone_name": "Washington Heights South",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.840015,
        "centroid_lon": -73.940015,
    },
    {
        "zone_id": 245,
        "borough": "Staten Island",
        "zone_name": "West Brighton",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.635015,
        "centroid_lon": -74.115015,
    },
    {
        "zone_id": 246,
        "borough": "Manhattan",
        "zone_name": "West Chelsea/Hudson Yards",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.752015,
        "centroid_lon": -74.004015,
    },
    {
        "zone_id": 247,
        "borough": "Bronx",
        "zone_name": "West Concourse",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.835015,
        "centroid_lon": -73.925015,
    },
    {
        "zone_id": 248,
        "borough": "Bronx",
        "zone_name": "West Farms/Bronx River",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.838015,
        "centroid_lon": -73.878015,
    },
    {
        "zone_id": 249,
        "borough": "Manhattan",
        "zone_name": "West Village",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.734015,
        "centroid_lon": -74.005015,
    },
    {
        "zone_id": 250,
        "borough": "Bronx",
        "zone_name": "Westchester Village/Unionport",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.835015,
        "centroid_lon": -73.848015,
    },
    {
        "zone_id": 251,
        "borough": "Staten Island",
        "zone_name": "Westerleigh",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.620015,
        "centroid_lon": -74.135015,
    },
    {
        "zone_id": 252,
        "borough": "Queens",
        "zone_name": "Whitestone",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.792015,
        "centroid_lon": -73.815015,
    },
    {
        "zone_id": 253,
        "borough": "Queens",
        "zone_name": "Willets Point",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.760015,
        "centroid_lon": -73.845015,
    },
    {
        "zone_id": 254,
        "borough": "Bronx",
        "zone_name": "Williamsbridge/Olinville",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.875015,
        "centroid_lon": -73.860015,
    },
    {
        "zone_id": 255,
        "borough": "Brooklyn",
        "zone_name": "Williamsburg (North Side)",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.718015,
        "centroid_lon": -73.958015,
    },
    {
        "zone_id": 256,
        "borough": "Brooklyn",
        "zone_name": "Williamsburg (South Side)",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.709015,
        "centroid_lon": -73.958015,
    },
    {
        "zone_id": 257,
        "borough": "Brooklyn",
        "zone_name": "Windsor Terrace",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.655015,
        "centroid_lon": -73.978015,
    },
    {
        "zone_id": 258,
        "borough": "Queens",
        "zone_name": "Woodhaven",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.692015,
        "centroid_lon": -73.858015,
    },
    {
        "zone_id": 259,
        "borough": "Bronx",
        "zone_name": "Woodlawn/Wakefield",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.898015,
        "centroid_lon": -73.865015,
    },
    {
        "zone_id": 260,
        "borough": "Queens",
        "zone_name": "Woodside",
        "service_zone": "Boro Zone",
        "centroid_lat": 40.748015,
        "centroid_lon": -73.902015,
    },
    {
        "zone_id": 261,
        "borough": "Manhattan",
        "zone_name": "World Trade Center",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.711015,
        "centroid_lon": -74.012015,
    },
    {
        "zone_id": 262,
        "borough": "Manhattan",
        "zone_name": "Yorkville East",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.776015,
        "centroid_lon": -73.946015,
    },
    {
        "zone_id": 263,
        "borough": "Manhattan",
        "zone_name": "Yorkville West",
        "service_zone": "Yellow Zone",
        "centroid_lat": 40.778015,
        "centroid_lon": -73.951015,
    },
    {
        "zone_id": 264,
        "borough": "Unknown",
        "zone_name": "NV",
        "service_zone": "N/A",
        "centroid_lat": 0.0,
        "centroid_lon": 0.0,
    },
    {
        "zone_id": 265,
        "borough": "Unknown",
        "zone_name": "NA",
        "service_zone": "N/A",
        "centroid_lat": 0.0,
        "centroid_lon": 0.0,
    },
]


def get_default_zones_map() -> Dict[int, ZoneData]:
    """Return a dictionary mapping zone_id to ZoneData dictionary."""
    return {zone["zone_id"]: zone for zone in DEFAULT_NYC_TAXI_ZONES}
