"""LLM Provider abstraction and fallback engine for the LangGraph Ops Copilot.

ADR-024:
- Primary LLM: Groq (llama-3.3-70b-versatile, fallback llama-3.1-8b-instant) for low-latency inference.
- Fallback LLM: Google Gemini (gemini-2.0-flash / gemini-1.5-flash) for high availability.
- Hermetic Mock Engine: Deterministic rule-based tool-dispatch and response synthesis for
  100% reliable CI and local testing without external API credentials.
- Explicit Labeling: All responses generated by the mock provider are explicitly tagged with
  provider="mock", model_name="mock-rule-engine", and prefixed with '[MOCK / OFFLINE MODE]'
  in the response text.
"""

import json
import logging
import os
import re
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

import requests

logger = logging.getLogger(__name__)

# Verified current model identifiers
DEFAULT_GROQ_PRIMARY_MODEL = "llama-3.3-70b-versatile"
DEFAULT_GROQ_FALLBACK_MODEL = "llama-3.1-8b-instant"
DEFAULT_GEMINI_PRIMARY_MODEL = "gemini-2.0-flash"
DEFAULT_GEMINI_FALLBACK_MODEL = "gemini-1.5-flash"


class ProviderError(Exception):
    """Base exception for LLM provider errors."""

    pass


class ProviderUnavailableError(ProviderError):
    """Raised when an LLM provider is requested but its credentials or service are missing."""

    pass


@dataclass
class LLMResponse:
    """Standardized response from an LLM provider."""

    content: str
    tool_calls: List[Dict[str, Any]] = field(default_factory=list)
    provider: str = "mock"
    model_name: str = "mock-rule-engine"
    raw_metadata: Dict[str, Any] = field(default_factory=dict)


class BaseLLMProvider(ABC):
    """Abstract base class for copilot LLM providers."""

    @property
    @abstractmethod
    def provider_name(self) -> str:
        """Name of the provider ('groq', 'gemini', 'mock')."""
        pass

    @property
    @abstractmethod
    def model_name(self) -> str:
        """Name of the active model."""
        pass

    @abstractmethod
    def generate(
        self,
        messages: List[Dict[str, str]],
        tools: Optional[List[Dict[str, Any]]] = None,
    ) -> LLMResponse:
        """Generate a response or tool calls from the provider."""
        pass


class GroqProvider(BaseLLMProvider):
    """Groq Cloud LLM provider using REST API with fast inference."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        model_name: Optional[str] = None,
        timeout: float = 8.0,
    ):
        self._api_key = api_key or os.getenv("GROQ_API_KEY", "").strip()
        if not self._api_key:
            raise ProviderUnavailableError("GROQ_API_KEY is not set.")
        self._model_name = (
            model_name
            or os.getenv("GROQ_MODEL", "").strip()
            or DEFAULT_GROQ_PRIMARY_MODEL
        )
        self._timeout = timeout
        self._endpoint = "https://api.groq.com/openai/v1/chat/completions"

    @property
    def provider_name(self) -> str:
        return "groq"

    @property
    def model_name(self) -> str:
        return self._model_name

    def generate(
        self,
        messages: List[Dict[str, str]],
        tools: Optional[List[Dict[str, Any]]] = None,
    ) -> LLMResponse:
        headers = {
            "Authorization": f"Bearer {self._api_key}",
            "Content-Type": "application/json",
        }
        payload: Dict[str, Any] = {
            "model": self._model_name,
            "messages": messages,
            "temperature": 0.1,
            "max_tokens": 1024,
        }
        if tools:
            payload["tools"] = tools
            payload["tool_choice"] = "auto"

        try:
            resp = requests.post(
                self._endpoint,
                headers=headers,
                json=payload,
                timeout=self._timeout,
            )
            if resp.status_code == 404 or resp.status_code == 400:
                # If primary model fails or is deprecated, attempt fallback model
                if self._model_name != DEFAULT_GROQ_FALLBACK_MODEL:
                    logger.warning(
                        "Groq model %s returned status %d. Falling back to %s",
                        self._model_name,
                        resp.status_code,
                        DEFAULT_GROQ_FALLBACK_MODEL,
                    )
                    payload["model"] = DEFAULT_GROQ_FALLBACK_MODEL
                    resp = requests.post(
                        self._endpoint,
                        headers=headers,
                        json=payload,
                        timeout=self._timeout,
                    )
            resp.raise_for_status()
            data = resp.json()

            choice = data["choices"][0]["message"]
            content = choice.get("content") or ""
            raw_tool_calls = choice.get("tool_calls") or []

            parsed_tool_calls = []
            for tc in raw_tool_calls:
                fn = tc.get("function", {})
                args = fn.get("arguments", "{}")
                if isinstance(args, str):
                    try:
                        args = json.loads(args)
                    except json.JSONDecodeError:
                        args = {}
                parsed_tool_calls.append(
                    {
                        "id": tc.get("id"),
                        "name": fn.get("name"),
                        "args": args,
                    }
                )

            return LLMResponse(
                content=content,
                tool_calls=parsed_tool_calls,
                provider=self.provider_name,
                model_name=payload["model"],
                raw_metadata=data.get("usage", {}),
            )
        except Exception as exc:
            logger.error("Groq generation failed: %s", exc)
            raise ProviderError(f"Groq API call failed: {exc}") from exc


class GeminiProvider(BaseLLMProvider):
    """Google Gemini LLM provider using Google Generative Language REST API."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        model_name: Optional[str] = None,
        timeout: float = 10.0,
    ):
        self._api_key = (
            api_key
            or os.getenv("GEMINI_API_KEY", "").strip()
            or os.getenv("GOOGLE_API_KEY", "").strip()
        )
        if not self._api_key:
            raise ProviderUnavailableError(
                "GEMINI_API_KEY or GOOGLE_API_KEY is not set."
            )
        self._model_name = (
            model_name
            or os.getenv("GEMINI_MODEL", "").strip()
            or DEFAULT_GEMINI_PRIMARY_MODEL
        )
        self._timeout = timeout

    @property
    def provider_name(self) -> str:
        return "gemini"

    @property
    def model_name(self) -> str:
        return self._model_name

    def _call_gemini_endpoint(
        self, model: str, contents: List[Dict[str, Any]]
    ) -> requests.Response:
        url = (
            f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent"
            f"?key={self._api_key}"
        )
        headers = {"Content-Type": "application/json"}
        payload = {
            "contents": contents,
            "generationConfig": {"temperature": 0.1, "maxOutputTokens": 1024},
        }
        return requests.post(url, headers=headers, json=payload, timeout=self._timeout)

    def generate(
        self,
        messages: List[Dict[str, str]],
        tools: Optional[List[Dict[str, Any]]] = None,
    ) -> LLMResponse:
        # Convert messages to Gemini contents format
        contents = []
        for msg in messages:
            role = "user" if msg.get("role") in ("user", "system") else "model"
            contents.append({"role": role, "parts": [{"text": msg.get("content", "")}]})

        try:
            resp = self._call_gemini_endpoint(self._model_name, contents)
            active_model = self._model_name
            if resp.status_code == 404 or resp.status_code == 400:
                # If primary model fails, fallback to secondary model
                if self._model_name != DEFAULT_GEMINI_FALLBACK_MODEL:
                    logger.warning(
                        "Gemini model %s returned status %d. Falling back to %s",
                        self._model_name,
                        resp.status_code,
                        DEFAULT_GEMINI_FALLBACK_MODEL,
                    )
                    active_model = DEFAULT_GEMINI_FALLBACK_MODEL
                    resp = self._call_gemini_endpoint(active_model, contents)

            resp.raise_for_status()
            data = resp.json()
            candidates = data.get("candidates", [])
            if not candidates:
                return LLMResponse(
                    content="",
                    provider=self.provider_name,
                    model_name=active_model,
                )

            parts = candidates[0].get("content", {}).get("parts", [])
            content_text = "".join(p.get("text", "") for p in parts if "text" in p)

            return LLMResponse(
                content=content_text,
                provider=self.provider_name,
                model_name=active_model,
                raw_metadata=data.get("usageMetadata", {}),
            )
        except Exception as exc:
            logger.error("Gemini generation failed: %s", exc)
            raise ProviderError(f"Gemini API call failed: {exc}") from exc


class MockLLMProvider(BaseLLMProvider):
    """Deterministic, rule-based mock LLM provider for hermetic testing and offline operation.

    Guarantees:
    1. Provider is explicitly labeled as 'mock'.
    2. Model is explicitly labeled as 'mock-rule-engine'.
    3. Every response begins with '[MOCK / OFFLINE MODE] '.
    4. Automatically routes common operational queries to allowlisted tools.
    """

    MOCK_HEADER = "[MOCK / OFFLINE MODE]"

    @property
    def provider_name(self) -> str:
        return "mock"

    @property
    def model_name(self) -> str:
        return "mock-rule-engine"

    def _detect_tool_calls(self, query: str, query_lower: str) -> List[Dict[str, Any]]:
        """Detect query intent and produce corresponding allowlisted tool calls."""
        tool_calls: List[Dict[str, Any]] = []

        zone_match = re.search(r"\bzone\s*(\d+)\b", query_lower)
        is_demand_query = any(
            k in query_lower for k in ["demand", "feature", "pickup", "volume"]
        )
        is_corridor_query = any(
            k in query_lower
            for k in ["corridor", "eta", "duration", "trip time", "travel time"]
        )
        corridor_match = re.search(
            r"\b(?:corridor\s*)?(\d+)[_\-\s]+(?:to\s+)?(\d+)\b", query_lower
        )

        if is_corridor_query and corridor_match:
            orig, dest = corridor_match.group(1), corridor_match.group(2)
            tool_calls.append(
                {
                    "id": "mock_call_corridor_features",
                    "name": "get_features",
                    "args": {"entity_type": "corridor", "entity_id": f"{orig}_{dest}"},
                }
            )
        elif is_demand_query and zone_match:
            tool_calls.append(
                {
                    "id": "mock_call_zone_features",
                    "name": "get_features",
                    "args": {
                        "entity_type": "zone",
                        "entity_id": str(zone_match.group(1)),
                    },
                }
            )
        elif any(
            k in query_lower
            for k in [
                "drift",
                "decay",
                "distribution shift",
                "evidently",
                "feature drift",
                "prediction drift",
                "data drift",
                "model decay",
                "performance decay",
            ]
        ):
            report_type = None
            if "feature" in query_lower or "data" in query_lower:
                report_type = "data_drift"
            elif "prediction" in query_lower:
                report_type = "prediction_drift"
            elif any(d in query_lower for d in ["performance", "decay", "mae", "rmse"]):
                report_type = "performance_decay"

            tool_calls.append(
                {
                    "id": "mock_call_drift_reports",
                    "name": "query_drift_reports",
                    "args": (
                        {"report_type": report_type, "limit": 5}
                        if report_type
                        else {"limit": 5}
                    ),
                }
            )
        elif "prediction" in query_lower:
            if zone_match:
                tool_calls.append(
                    {
                        "id": "mock_call_predictions_zone",
                        "name": "query_recent_predictions",
                        "args": {
                            "entity_type": "zone",
                            "entity_id": zone_match.group(1),
                        },
                    }
                )
            elif corridor_match:
                orig, dest = corridor_match.group(1), corridor_match.group(2)
                tool_calls.append(
                    {
                        "id": "mock_call_predictions_corridor",
                        "name": "query_recent_predictions",
                        "args": {
                            "entity_type": "corridor",
                            "entity_id": f"{orig}_{dest}",
                        },
                    }
                )
            else:
                tool_calls.append(
                    {
                        "id": "mock_call_predictions_general",
                        "name": "query_recent_predictions",
                        "args": {
                            "entity_type": "zone",
                            "entity_id": "161",
                            "window_hours": 24,
                        },
                    }
                )
        elif any(
            k in query_lower
            for k in [
                "pipeline",
                "retrain",
                "batch",
                "health",
                "airflow",
                "prefect",
                "flow",
            ]
        ):
            tool_calls.append(
                {
                    "id": "mock_call_pipeline_status",
                    "name": "query_pipeline_status",
                    "args": {},
                }
            )
        elif any(
            k in query_lower
            for k in [
                "why nyc",
                "karachi",
                "hurdle rate",
                "adr",
                "architecture",
                "model card",
                "metrics",
                "lightgbm",
                "baseline",
                "feast",
                "faiss",
                "documentation",
            ]
        ):
            tool_calls.append(
                {
                    "id": "mock_call_rag_search",
                    "name": "search_logs_and_model_cards",
                    "args": {"query": query, "top_k": 3},
                }
            )

        return tool_calls

    def generate(
        self,
        messages: List[Dict[str, str]],
        tools: Optional[List[Dict[str, Any]]] = None,
    ) -> LLMResponse:
        last_user_msg = ""
        for m in reversed(messages):
            if m.get("role") == "user":
                last_user_msg = m.get("content", "")
                break

        query = last_user_msg.strip()
        query_lower = query.lower()

        tool_calls = self._detect_tool_calls(query, query_lower)

        if tool_calls and tools:
            return LLMResponse(
                content="",
                tool_calls=tool_calls,
                provider=self.provider_name,
                model_name=self.model_name,
            )

        content = self.synthesize_direct_response(query)
        return LLMResponse(
            content=content,
            tool_calls=[],
            provider=self.provider_name,
            model_name=self.model_name,
        )

    def synthesize_direct_response(self, query: str) -> str:
        """Synthesize a direct natural language response with mandatory mock header."""
        query_lower = query.lower()
        if any(g in query_lower for g in ["hello", "hi", "hey", "who are you", "help"]):
            body = (
                "Greetings! I am the Logistics Demand & ETA Ops Copilot. "
                "I can inspect live feature values from Feast Redis, query recent predictions from PostgreSQL, "
                "summarize pipeline execution health, inspect Evidently drift and model performance reports, "
                "or explain architectural decisions from platform documentation. "
                "How can I assist your operations today?"
            )
        else:
            body = (
                f"I processed your query: '{query}'. "
                "In offline/mock mode, operational queries regarding taxi zone demand, corridor trip durations, "
                "pipeline runs, model drift reports, or architecture decisions are routed through read-only tools."
            )

        return f"{self.MOCK_HEADER} {body}"


def get_llm_provider(force_provider: Optional[str] = None) -> BaseLLMProvider:
    """Retrieve an LLM provider based on configuration or automated fallback hierarchy.

    Fallback Hierarchy:
    1. If force_provider='mock' -> MockLLMProvider()
    2. If force_provider='groq' -> GroqProvider()
    3. If force_provider='gemini' -> GeminiProvider()
    4. Check GROQ_API_KEY -> GroqProvider() if valid
    5. Check GEMINI_API_KEY/GOOGLE_API_KEY -> GeminiProvider() if valid
    6. Default fallback -> MockLLMProvider()

    Args:
        force_provider: Optional override ('groq', 'gemini', 'mock').

    Returns:
        Configured BaseLLMProvider instance.
    """
    pref = str(force_provider).strip().lower() if force_provider else None

    if pref == "mock":
        return MockLLMProvider()
    elif pref == "groq":
        return GroqProvider()
    elif pref == "gemini":
        return GeminiProvider()

    # Cascade auto-selection
    if os.getenv("GROQ_API_KEY", "").strip():
        try:
            return GroqProvider()
        except ProviderUnavailableError:
            pass

    if (
        os.getenv("GEMINI_API_KEY", "").strip()
        or os.getenv("GOOGLE_API_KEY", "").strip()
    ):
        try:
            return GeminiProvider()
        except ProviderUnavailableError:
            pass

    logger.info(
        "No external LLM API credentials detected. Initializing hermetic MockLLMProvider."
    )
    return MockLLMProvider()
